In [1]:
3 + 5

[1] 8

In [2]:
10 - 3

[1] 7

In [3]:
sqrt(16)

[1] 4

In [4]:
log(2, base = 10)

[1] 0.30103

In [5]:
date()

[1] "Sun Feb 24 04:03:55 2019"

In [6]:
date()

[1] "Sun Feb 24 04:03:55 2019"

In [7]:
summary(c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192))

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  173.0   175.0   179.0   179.4   181.5   192.0 

In [8]:
heights <- c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192)

In [9]:
heights

[1] 173 178 180 183 182 174 179 179 174 192

In [10]:
hawks <-  matrix(c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192, 1700, 1400, 9000, 5000, 3000, 120000,90, 2100, 1000, 25000), 10, 2)

In [11]:
hawks

[,1] [,2]  
 [1,] 173    1700
 [2,] 178    1400
 [3,] 180    9000
 [4,] 183    5000
 [5,] 182    3000
 [6,] 174  120000
 [7,] 179      90
 [8,] 179    2100
 [9,] 174    1000
[10,] 192   25000

In [12]:
license()


This software is distributed under the terms of the GNU General
Public License, either Version 2, June 1991 or Version 3, June 2007.
The terms of version 2 of the license are in a file called COPYING
which you should have received with
this software and which can be displayed by RShowDoc("COPYING").
Version 3 of the license can be displayed by RShowDoc("GPL-3").

Copies of both versions 2 and 3 of the license can be found
at https://www.R-project.org/Licenses/.

A small number of files (the API header files listed in
R_DOC_DIR/COPYRIGHTS) are distributed under the
LESSER GNU GENERAL PUBLIC LICENSE, version 2.1 or later.
This can be displayed by RShowDoc("LGPL-2.1"),
or obtained at the URI given.
Version 3 of the license can be displayed by RShowDoc("LGPL-3").

'Share and Enjoy.'



In [13]:
demo()

In [14]:
matrix(c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192, 1700, 1400, 9000, 5000, 3000, 120000,90, 2100, 1000, 25000), 10, 3)

Warning message in matrix(c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192, 1700, :
“data length [20] is not a sub-multiple or multiple of the number of columns [3]”

[,1] [,2]   [,3]
 [1,] 173    1700 173 
 [2,] 178    1400 178 
 [3,] 180    9000 180 
 [4,] 183    5000 183 
 [5,] 182    3000 182 
 [6,] 174  120000 174 
 [7,] 179      90 179 
 [8,] 179    2100 179 
 [9,] 174    1000 174 
[10,] 192   25000 192

In [15]:
matrix(c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192, 1700, 1400, 9000, 5000, 3000, 120000,90, 2100, 1000, 25000), 9, 2)

Warning message in matrix(c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192, 1700, :
“data length [20] is not a sub-multiple or multiple of the number of rows [9]”

[,1] [,2]  
 [1,] 173     192
 [2,] 178    1700
 [3,] 180    1400
 [4,] 183    9000
 [5,] 182    5000
 [6,] 174    3000
 [7,] 179  120000
 [8,] 179      90
 [9,] 174    2100

In [16]:
matrix(c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192, 1700, 1400, 9000, 5000, 3000, 120000,90, 2100, 1000, 25000), 11, 3)

Warning message in matrix(c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192, 1700, :
“data length [20] is not a sub-multiple or multiple of the number of rows [11]”

[,1] [,2]   [,3]
 [1,]  173   1400  180
 [2,]  178   9000  183
 [3,]  180   5000  182
 [4,]  183   3000  174
 [5,]  182 120000  179
 [6,]  174     90  179
 [7,]  179   2100  174
 [8,]  179   1000  192
 [9,]  174  25000 1700
[10,]  192    173 1400
[11,] 1700    178 9000

In [17]:
matrix(c(173, 178, 180, 183, 182, 174, 179, 179, 174, 192, 1700, 1400, 9000, 5000, 3000, 120000,90, 2100, 1000, 25000), 10, 1)

[,1]
 [1,] 173 
 [2,] 178 
 [3,] 180 
 [4,] 183 
 [5,] 182 
 [6,] 174 
 [7,] 179 
 [8,] 179 
 [9,] 174 
[10,] 192